name: Run Tests

on:
  push:
    branches:
      - main
      - dev  # Change this to your branch name if needed
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Change to your required Node.js version

      - name: Navigate to MSN directory
        run: cd MSN

      - name: Install dependencies
        run: npm install
        working-directory: MSN # Ensures npm install runs inside MSN directory

      - name: Run Tests
        run: npm test
        working-directory: MSN
