name: Run Tests with Server

on:
  push:
    branches:
      - "**"
      - "dev"
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure Jest can compare against origin/main

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
        working-directory: MSN

      - name: Start Server in Background
        run: npm start &
        working-directory: MSN

      - name: Wait for Server to Start
        run: sleep 10

      - name: Build
        run: npm run build --if-present
        working-directory: MSN

      - name: Run Jest Test Discovery (Debugging)
        run: npx jest --listTests
        working-directory: MSN

      - name: Run Tests
        run: npm run test -- --coverage=true
        working-directory: MSN

      - name: Prebuild Expo Project
        run: npx expo prebuild --android
        working-directory: MSN

      - name: Build Android Release APK
        run: ./gradlew assembleRelease
        working-directory: MSN/android

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Android Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: MSN/android/app/build/outputs/apk/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: saisandeepramavath/SWEN732PROJ
          files: MSN/coverage/lcov.info